export const mindMapData = {
  nodes: [
    { id: "미국", category: "center" },
    { id: "인도", category: "blue" },
    { id: "강화", category: "yellow" },
    { id: "해외", category: "coral" },
    { id: "안정적", category: "green" },
    { id: "차량", category: "blue" },
    { id: "소비자", category: "lightblue" },
    { id: "경기변동", category: "blue" },
    { id: "공장", category: "blue" },
    { id: "유럽", category: "coral" },
    { id: "자동차", category: "turquoise" },
    { id: "임상", category: "turquoise" },
    { id: "시장점유율", category: "turquoise" },
    { id: "치료제", category: "blue" },
    { id: "일본", category: "coral" },
    { id: "국내", category: "coral" },
    { id: "중국", category: "coral" },
    { id: "가다", category: "yellow" },
    { id: "정책", category: "green" },
    { id: "바이오", category: "turquoise" },
    { id: "국가", category: "green" },
    { id: "한국", category: "coral" },
    { id: "증가", category: "blue" },
    { id: "연구개발", category: "yellow" },
    { id: "독일", category: "lightblue" },
    { id: "시험", category: "blue" },
    { id: "의약품", category: "blue" },
    { id: "아시아", category: "green" },
    { id: "시장", category: "coral" },
  ],
  links: [
    { source: "미국", target: "인도" },
    { source: "미국", target: "강화" },
    { source: "미국", target: "해외" },
    { source: "미국", target: "안정적" },
    { source: "미국", target: "차량" },
    { source: "미국", target: "소비자" },
    { source: "미국", target: "경기변동" },
    { source: "미국", target: "공장" },
    { source: "미국", target: "유럽" },
    { source: "미국", target: "자동차" },
    { source: "미국", target: "임상" },
    { source: "미국", target: "시장점유율" },
    { source: "미국", target: "치료제" },
    { source: "미국", target: "일본" },
    { source: "미국", target: "국내" },
    { source: "미국", target: "중국" },
    { source: "미국", target: "가다" },
    { source: "미국", target: "정책" },
    { source: "미국", target: "바이오" },
    { source: "미국", target: "국가" },
    { source: "미국", target: "한국" },
    { source: "미국", target: "증가" },
    { source: "미국", target: "연구개발" },
    { source: "미국", target: "독일" },
    { source: "미국", target: "시험" },
    { source: "미국", target: "의약품" },
    { source: "미국", target: "아시아" },
    { source: "미국", target: "시장" },
  ],
};

export const mindMapColorData = {
  center: "#333333",
  blue: "#4B89DC",
  yellow: "#F1C40F",
  coral: "#FF7473",
  green: "#2ECC71",
  lightblue: "#5DADE2",
  turquoise: "#1ABC9C",
};
export const colorName = [
  // "center",
  "blue",
  "yellow",
  "coral",
  "green",
  "lightblue",
  "turquoise",
];
