FROM openjdk:17

WORKDIR /app

Run ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8002

ENTRYPOINT ["java", "-jar", "app.jar"]